
package main.cinemaproject.view.Admin;

import java.util.ArrayList;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import main.cinemaproject.controller.MovieController;
import main.cinemaproject.model.Movie;


/**
 *
 * @author DinhAn
 */
public class QuanLyPhim extends javax.swing.JPanel {

    private MovieController movieController;
    /**
     * Creates new form QuanLyPhim
     */
    public QuanLyPhim() {
        initComponents();
        movieController = new MovieController();
        showMovieTable();
        //change the size of the table
        BangPhim.setRowHeight(BangPhim.getRowHeight() + 5);
    }

    //get all movies
    public ArrayList<Movie> mList() throws SQLException
    {
        return movieController.getAllMovies();
    }

    //put movies into table
    public void showMovieTable()
    {
        ArrayList<Movie> mTable;
        try {
            mTable = mList();
        }
        catch(SQLException e)
        {
            System.out.println("vkl loi : "+e.getMessage());
            return;
        }

        DefaultTableModel model = (DefaultTableModel) BangPhim.getModel();
        model.setRowCount(0);

        for(Movie m: mTable)
        {
            model.addRow(new Object[]{
                m.getId(),
                m.getName(),
                m.getGenre(),
                m.getDirector(),
                m.getReleaseDate(),
                m.getDuration()
            });
        }

        //tự động điều chỉnh kích thước các cột
        BangPhim.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chonLich = new com.raven.datechooser.DateChooser();
        bangThemPhim = new javax.swing.JPanel();
        TenPhimText = new javax.swing.JTextField();
        TheLoaiText = new javax.swing.JTextField();
        DaoDienText = new javax.swing.JTextField();
        NgayCongChieuText = new javax.swing.JTextField();
        ThoiLuongText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ThemBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangPhim = new javax.swing.JTable();

        chonLich.setForeground(new java.awt.Color(0, 153, 51));
        chonLich.setDateFormat("yyyy-MM-dd");
        chonLich.setTextRefernce(NgayCongChieuText);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bangThemPhim.setBackground(new java.awt.Color(255, 255, 255));
        bangThemPhim.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm Phim Mới"));

        TheLoaiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLoaiTextActionPerformed(evt);
            }
        });

        DaoDienText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaoDienTextActionPerformed(evt);
            }
        });

        ThoiLuongText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoiLuongTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên Phim");

        jLabel2.setText("Thể Loại");

        jLabel3.setText("Đạo Diễn");

        jLabel4.setText("Ngày Công Chiếu");

        jLabel5.setText("Thời Lượng");

        ThemBut.setText("Thêm ");
        ThemBut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ThemBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bangThemPhimLayout = new javax.swing.GroupLayout(bangThemPhim);
        bangThemPhim.setLayout(bangThemPhimLayout);
        bangThemPhimLayout.setHorizontalGroup(
            bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangThemPhimLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bangThemPhimLayout.createSequentialGroup()
                        .addComponent(TheLoaiText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(bangThemPhimLayout.createSequentialGroup()
                        .addComponent(TenPhimText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(6, 6, 6)
                .addGroup(bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DaoDienText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayCongChieuText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThoiLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(ThemBut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        bangThemPhimLayout.setVerticalGroup(
            bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangThemPhimLayout.createSequentialGroup()
                .addGroup(bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bangThemPhimLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TenPhimText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DaoDienText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThoiLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(bangThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TheLoaiText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgayCongChieuText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)))
                    .addGroup(bangThemPhimLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ThemBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(bangThemPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 880, 170));

        BangPhim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Phim", "Thể Loại", "Đạo Diễn", "Ngày Công Chiếu", "Thời Lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BangPhim);
        if (BangPhim.getColumnModel().getColumnCount() > 0) {
            BangPhim.getColumnModel().getColumn(0).setResizable(false);
            BangPhim.getColumnModel().getColumn(1).setResizable(false);
            BangPhim.getColumnModel().getColumn(2).setResizable(false);
            BangPhim.getColumnModel().getColumn(3).setResizable(false);
            BangPhim.getColumnModel().getColumn(4).setResizable(false);
            BangPhim.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 880, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void TheLoaiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheLoaiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheLoaiTextActionPerformed

    private void DaoDienTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaoDienTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DaoDienTextActionPerformed

    private void ThoiLuongTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoiLuongTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThoiLuongTextActionPerformed

    private void ThemButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButActionPerformed
        //lấy các thông tin từ textfield
        String name = TenPhimText.getText().trim();
        String genre = TheLoaiText.getText().trim();
        String Director = DaoDienText.getText().trim();
        String releaseDate = NgayCongChieuText.getText().trim();
        String durationText = ThoiLuongText.getText().trim();

        //kiểm tra các điều kiện
        if (name.isEmpty() || genre.isEmpty() || Director.isEmpty() || releaseDate.isEmpty() || ThoiLuongText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
            return;
        }
        
        //chuyển thời lượng về số nguyên
        int duration;
        try
        {
            duration = Integer.parseInt(durationText);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Thời lượng phải là một số hợp lệ.");
            return;
        }

        //tạo một đối tượng phim mới
        Movie newMovie = new Movie(name, genre, releaseDate, Director, duration);
        
        //thêm phim mới vào cơ sở dữ liệu
        movieController.addMovie(newMovie);
        
        //Thông báo thêm thành công
        JOptionPane.showMessageDialog(this, "Thêm phim thành công.");
    
        //hiển thị lại bảng phim
        showMovieTable();
    }//GEN-LAST:event_ThemButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangPhim;
    private javax.swing.JTextField DaoDienText;
    private javax.swing.JTextField NgayCongChieuText;
    private javax.swing.JTextField TenPhimText;
    private javax.swing.JTextField TheLoaiText;
    private javax.swing.JButton ThemBut;
    private javax.swing.JTextField ThoiLuongText;
    private javax.swing.JPanel bangThemPhim;
    private com.raven.datechooser.DateChooser chonLich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
