package main.cinemaproject.view.Admin;

import main.cinemaproject.controller.MovieController;
import main.cinemaproject.controller.TheaterController;
import main.cinemaproject.controller.ScreeningStatusController;
import main.cinemaproject.model.Movie;
import main.cinemaproject.model.Theater;
import main.cinemaproject.model.ScreeningStatus;
import main.cinemaproject.utils.TimeConverter;
import main.cinemaproject.utils.ValidationUtils;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.util.List;

/**
 *
 * @author DinhAn
 */
public class ThemSuat extends javax.swing.JFrame {
    private MovieController movieController;
    private TheaterController theaterController;
    private ScreeningStatusController screeningStatusController;

    /**
     * Creates new form ThemSuat
     */
    public ThemSuat() {
        initComponents();
        movieController = new MovieController();
        theaterController = new TheaterController();
        screeningStatusController = new ScreeningStatusController();
        loadMovies();
        loadTheaters();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bangChonNgay = new com.raven.datechooser.DateChooser();
        bangChonGio = new com.raven.swing.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chonPhim = new javax.swing.JComboBox<>();
        chonRap = new javax.swing.JComboBox<>();
        chonNgay = new javax.swing.JTextField();
        chonGio = new javax.swing.JTextField();
        themBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chonGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        popup = new javax.swing.JButton();

        bangChonNgay.setForeground(new java.awt.Color(0, 153, 51));
        bangChonNgay.setDateFormat("yyyy-MM-dd");
        bangChonNgay.setTextRefernce(chonNgay);

        bangChonGio.setForeground(new java.awt.Color(0, 153, 51));
        bangChonGio.setDisplayText(chonGio);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thêm Suất Chiếu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel2)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        jPanel3.setBackground(new java.awt.Color(231, 231, 231));

        jLabel1.setText("Chọn Phim");

        chonPhim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chonRap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        themBut.setText("Thêm");
        themBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButActionPerformed(evt);
            }
        });

        jLabel3.setText("Chọn Rạp");

        jLabel4.setText("Chọn Giờ");

        jLabel5.setText("Chọn Ngày");

        jLabel6.setText("Giá");

        popup.setText("Chọn Giờ");
        popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chonPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(160, 160, 160)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chonGio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chonRap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(popup)))
                            .addComponent(chonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(themBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chonRap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chonPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(chonGio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(popup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addComponent(themBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 690, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMouseClicked
        bangChonGio.showPopup(this, 100, 100);
    }//GEN-LAST:event_popupMouseClicked

    private void themButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButActionPerformed
        String selectedMovie = (String) chonPhim.getSelectedItem();
        String selectedTheater = (String) chonRap.getSelectedItem();
        String showtimeStr = chonGio.getText(); // Định dạng hh:mm AM/PM
        String showdateStr = chonNgay.getText(); // Định dạng yyyy-MM-dd
        String priceStr = chonGia.getText(); // Chuỗi giá vé
        int availableSeat = 20;
        int totalSeat = 20;

        // Kiểm tra đầu vào
        if (selectedMovie.isEmpty() || selectedTheater.isEmpty() || showtimeStr.isEmpty() || showdateStr.isEmpty() || priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        // Kiểm tra định dạng giờ chiếu
        if (!ValidationUtils.isValidTime(showtimeStr)) {
            JOptionPane.showMessageDialog(this, "Định dạng giờ chiếu không đúng. Vui lòng nhập lại!");
            return;
        }

        // Kiểm tra định dạng ngày chiếu
        // if (!ValidationUtils.isValidDate(showdateStr)) {
        //     JOptionPane.showMessageDialog(this, "Định dạng ngày chiếu không đúng. Vui lòng nhập lại!");
        //     return;
        // }

        // Kiểm tra giá vé
        try {
            double price = Double.parseDouble(priceStr);
            if (price <= 0) {
                JOptionPane.showMessageDialog(this, "Giá vé phải lớn hơn 0!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá vé không đúng định dạng. Vui lòng nhập lại!");
            return;
        }

        // Chuyển đổi thời gian từ chuỗi sang java.sql.Time
        java.sql.Time showtime = TimeConverter.convertToSqlTime(showtimeStr);
        Date showdate = Date.valueOf(showdateStr); // Chuyển đổi chuỗi sang java.sql.Date

        // Tạo đối tượng ScreeningStatus bằng constructor có tham số
        ScreeningStatus screening = new ScreeningStatus();
        screening.setMovieId(movieController.getMovieId(selectedMovie)); // Lấy ID phim
        screening.setTheaterId(theaterController.getTheaterId(selectedTheater)); // Lấy ID rạp
        screening.setShowtime(showtime);
        screening.setShowdate(showdate);
        screening.setSeatsAvailable(availableSeat);
        screening.setTotalSeats(totalSeat);
        screening.setPrice(Double.parseDouble(priceStr)); // Lấy giá từ jTextField1

        // Gọi phương thức thêm screening status
        boolean success = screeningStatusController.addScreening(screening);

        if (success) {
            JOptionPane.showMessageDialog(this, "Thêm suất chiếu thành công!");
            QuanLySuatChieu.refreshScreeningData();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm suất chiếu thất bại!");
        }
    }//GEN-LAST:event_themButActionPerformed

    private void loadMovies() {
        List<Movie> movies = movieController.getAllMovies();
        DefaultComboBoxModel<String> movieModel = new DefaultComboBoxModel<>();
        
        for (Movie movie : movies) {
            movieModel.addElement(movie.getName());
        }
        
        chonPhim.setModel(movieModel);
    }

    private void loadTheaters() {
        List<Theater> theaters = theaterController.getAllTheaters();
        DefaultComboBoxModel<String> theaterModel = new DefaultComboBoxModel<>();
        
        for (Theater theater : theaters) {
            theaterModel.addElement(theater.getName());
        }
        
        chonRap.setModel(theaterModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.TimePicker bangChonGio;
    private com.raven.datechooser.DateChooser bangChonNgay;
    private javax.swing.JTextField chonGia;
    private javax.swing.JTextField chonGio;
    private javax.swing.JTextField chonNgay;
    private javax.swing.JComboBox<String> chonPhim;
    private javax.swing.JComboBox<String> chonRap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton popup;
    private javax.swing.JButton themBut;
    // End of variables declaration//GEN-END:variables
}
